
services:
  secrets-finder-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5200:5200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: secrets-finder-app
    restart: unless-stopped